---
- name: read ssh port
  shell: "grep ^Port /etc/ssh/sshd_config | tr -dc '0-9'"
  register: grep_ssh_port

- name: set fact ssh port
  set_fact:
    common_ssh_port: "{{ grep_ssh_port.stdout }}"
  when: grep_ssh_port.stdout|length > 0

- name: set fact ssh port
  set_fact:
    common_ssh_port: 22
  when: grep_ssh_port.stdout|length == 0

- name: ufw deny all
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  environment:
    PATH: /sbin:{{ ansible_env.PATH }}

- name: ufw allow ssh
  ufw:
    direction: incoming
    policy: allow
    port: "{{ common_ssh_port | string }}"
    proto: tcp
  environment:
    PATH: /sbin:{{ ansible_env.PATH }}

- name: ufw limit ssh
  ufw:
    direction: in
    rule: limit
    port: "{{ common_ssh_port | string }}"
    proto: tcp
    delete: yes # due to issues with ssh-tunnels for control-center (python & electron)
  environment:
    PATH: /sbin:{{ ansible_env.PATH }}

# EOF
