---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install pip
  yum:
    name: python3-pip
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install pexpect
  pip:
    name: pexpect

- name: Moving keystore backup to launchpad
  shell: "mv {{ e2dc_install_path }}/launchpad/keystore_backup/{{ validator_keystore }} {{ e2dc_install_path }}/launchpad/"
  become: yes

- name: Run exit validator
  ansible.builtin.expect:
    command: "docker-compose -f exit-account.yaml run -e LAUNCHPADDIR='/opt/app/launchpad/{{ validator_keystore }}' exit-validator"
    timeout: 10
    responses:
      'Enter the keystore password for validator': "{{ validator_password }}"
      'Enter the exit phrase from the above URL': "Exit my validator"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: true
  register: exit_output
  when: setups[setup].exit_account is defined

- name: Moving keystore file to backup
  shell: "mv {{ e2dc_install_path }}/launchpad/{{ validator_keystore }} {{ e2dc_install_path }}/launchpad/keystore_backup"
  become: yes

- name: error validator is exited
  fail:
    msg: "This validator is already exited, status: Exited and Unslashed"
  become: yes
  when: "'Validator status: ExitedUnslashed' in exit_output.stdout"  

# EOF  
