---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: Moving keystore backup to launchpad
  shell: "mv {{ e2dc_install_path }}/launchpad/keystore_backup/{{ validator_keystore }} {{ e2dc_install_path }}/launchpad/"
  become: yes

- name: Run exit validator
  ansible.builtin.expect:
    command: "docker-compose -f exit-account.yaml run -e LAUNCHPADDIR='/opt/app/launchpad/{{ validator_keystore }}' exit-validator"
    timeout: 10
    responses:
      'Enter the keystore password for validator': "{{ validator_password }}"
      'Enter the exit phrase from the above URL': "Exit my validator"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: true
  when: setups[setup].exit_account is defined

- name: Moving keystore file to backup
  shell: "mv {{ e2dc_install_path }}/launchpad/{{ validator_keystore }} {{ e2dc_install_path }}/launchpad/keystore_backup"
  become: yes

# EOF  
