---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: call stop-services role
      include_role:
        name: stop-services   

    - name: Checking imported keys of teku
      include_role:
        name: check-imported-keys-teku
      when: setup == "teku" and exported_config_path is not defined

    - name: Create validator keys
      copy:
        dest: "{{ e2dc_install_path }}/launchpad/{{ item.name }}"
        content: "{{ item.content }}"
      become: yes
      with_items: "{{validator_keys}}"
      when: validator_keys is defined 

    - name: Copy lanchpad wallet's validator keys
      shell: "cp {{ validator_keys_path }}/keystore-*.json {{ e2dc_install_path }}/launchpad"
      become: yes
      when: setup != "multiclient" and validator_keys_path is defined

    - name: Copy lanchpad wallet's validator keys 'config-import'
      shell: "cp /tmp/exported-config/keystore-*.json {{ e2dc_install_path }}/launchpad"
      become: yes
      when: exported_config_path is defined and setup != "multiclient"

    - name: Set permissions of import folder
      shell: "chown -R {{ stereum_user }}:{{ stereum_user }} {{ e2dc_install_path }}/launchpad"
      become: yes
      when: setup != "multiclient"

    - block:
      - name: import to lighthouse
        include_role:
          name: import-validator-keys-lighthouse
        when: setup == "lighthouse"
      ignore_errors: yes

    - block:
      - name: import to lodestar
        include_role:
          name: import-validator-keys-lodestar
        when: setup == "lodestar"
      ignore_errors: yes

    - block:
      - name: import to nimbus
        include_role:
          name: import-validator-keys-nimbus
        when: setup == "nimbus"
      ignore_errors: yes

    - block:
      - name: import to prysm
        include_role:
          name: import-validator-keys-prysm
        when: setup == "prysm"
      ignore_errors: yes

    - block:
      - name: import to teku
        include_role:
          name: import-validator-keys-teku
        when: setup == "teku"
      ignore_errors: yes

    - block:
      - name: import to multiclient
        include_role:
          name: import-validator-keys-multiclient
        when: setup == "multiclient"
      ignore_errors: yes

    - name: call start-services role
      include_role:
        name: start-services

    - name: Checking keys' password of teku
      include_role:
        name: check-keys-password-teku
      when: setup == "teku" 

    - name: Remove exported-config directory
      file:
        path: "/tmp/exported-config"
        state: absent
      when: validator_password is defined and exported_config_path is defined 

# EOF  
