---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: Extract Multiclient's wallet 'import-config'
      include_role:
        name: extract-wallet-multiclient
      when: setup == "multiclient" and exported_config_path is defined  

    - name: Check - key files exists
      include_role:
        name: check-keys-exists   

    - name: Checking imported keys of teku
      include_role:
        name: check-imported-keys-teku
      when: setup == "teku" and exported_config_path is not defined

    - name: Copy validator keys to launchpad directory
      include_role:
        name: copy-validator-keys-to-launchpad

    - block:
      - name: import to lighthouse
        include_role:
          name: import-validator-keys-lighthouse
        when: setup == "lighthouse"
      ignore_errors: yes

    - block:
      - name: import to lodestar
        include_role:
          name: import-validator-keys-lodestar
        when: setup == "lodestar"
      ignore_errors: yes

    - block:
      - name: import to nimbus
        include_role:
          name: import-validator-keys-nimbus
        when: setup == "nimbus"
      ignore_errors: yes

    - block:
      - name: import to prysm
        include_role:
          name: import-validator-keys-prysm
        when: setup == "prysm"
      ignore_errors: yes

    - block:
      - name: import to teku
        include_role:
          name: import-validator-keys-teku
        when: setup == "teku"
      ignore_errors: yes

    - block:
      - name: import to multiclient
        include_role:
          name: import-validator-keys-multiclient
        when: setup == "multiclient"
      ignore_errors: yes

    - name: call stop-services role
      include_role:
        name: stop-services  

    - name: call start-services role
      include_role:
        name: start-services

    - name: Checking keys' password of teku
      include_role:
        name: check-keys-password-teku
      when: setup == "teku" 

    - name: Remove exported-config directory
      file:
        path: "/tmp/exported-config"
        state: absent
      become: yes  
      when: validator_password is defined and exported_config_path is defined 

# EOF  
