---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  roles:
    - role: stop-services
    - role: configure-os-security
    - role: set-api-bind-address
    - role: start-services

# EOF
