---
- name: Check validator keys exists CLI
  find:
    paths: "{{ validator_keys_path }}"
    patterns: "keystore-*.json"
  register: keystore_files
  become: yes
  when: setup != "multiclient" and validator_keys_path is defined

- name: Error - No Validators found!
  fail:
    msg: "No validators found!"
  when: ((setup != "multiclient" and validator_keys_path is defined) and keystore_files.matched < 1)    

- name: Check validator keys exists 'import-config'
  find:
    paths: /tmp/exported-config
    patterns: "keystore-*.json"
  register: keystore_files
  become: yes
  when: setup != "multiclient" and exported_config_path is defined

- name: Error - No Validators found!
  fail:
    msg: "No validators found!"
  when: ((setup != "multiclient" and exported_config_path is defined) and keystore_files.matched < 1)  

- name: Check wallet exists multiclient 'import-config'
  stat:
    path: /tmp/exported-config/wallet
  register: wallet
  become: yes
  when: setup == "multiclient" and exported_config_path is defined  

- name: Error - No Wallet found!
  fail:
    msg: "No Wallet found!"
  when: ((setup == "multiclient" and exported_config_path is defined) and not wallet.stat.exists)

# EOF  
