---
- name: Copy docker-compose.yaml
  command: "cp 'compose-examples/{{ setups[setup].compose_path }}' 'docker-compose.yaml'"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

# EOF 
