---
- name: Run delete keystores directory
  ansible.builtin.file:
    path: "{{ e2dc_install_path }}/data/lodestar/validator/keystores/{{ validator_pubkey }}"
    state: absent
  become: yes

- name: Run delete secrets file
  ansible.builtin.file:
    path: "{{ e2dc_install_path }}/data/lodestar/validator/secrets/{{ validator_pubkey }}"
    state: absent
  become: yes

- name: Separate 0x from public key
  shell: "printf {{ validator_pubkey }} | tail -c 96"
  register: pubkey_without_0x
  become: yes

- name: Remove keystore file from launchpad
  shell: "grep -l {{ pubkey_without_0x.stdout_lines[0] }} * | xargs rm"
  args:
    chdir: "{{ e2dc_install_path }}/launchpad"
  become: yes

# EOF  
