---
- name: Export config - ethereum2.yaml file
  ansible.builtin.expect:
    command: /usr/local/bin/age/age -e -p --output /tmp/exported-config/exported_config.age /etc/stereum/ethereum2.yaml
    timeout: "300"
    responses:
       Enter passphrase: "{{ export_config_password | quote }}"
       Confirm passphrase: "{{ export_config_password | quote }}"
  become: yes

- name: Export keystore files
  copy:
    src: "{{ item }}"
    dest: /tmp/exported-config
    mode: '0755'
  with_fileglob:
    - "{{ e2dc_install_path }}/launchpad/keystore-*.json"
  become: yes

- name: Set exported config dir's permission
  ansible.builtin.file:
    path: /tmp/exported-config
    mode: '755'
    recurse: yes
  become: yes

# EOF
