---
- name: Install git
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - git
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install git
  yum:
    name: git
    state: latest
  become: yes
  when: ansible_distribution == "CentOS"

- name: Clone Ethereum 2.0 docker compose setup
  git:
    repo: "https://github.com/stereum-dev/ethereum2-docker-compose.git"
    dest: "{{ install_e2dc_install_path }}"
    force: yes
  become: yes

- name: Change file ownership and group of clone
  file:
    state: directory
    path: "{{ install_e2dc_install_path }}"
    owner: "{{ stereum_user }}"
    group: "{{ stereum_user }}"
    recurse: yes
  become: yes
