---
- name: Run list validators
  shell: "docker exec -it stereum_validator_1 /app/cmd/validator/validator accounts list --wallet-dir=\"/data/wallets\" --wallet-password-file=\"/data/passwords/wallet-password\" --accept-terms-of-use=\"true\""
  ignore_errors: yes
  register: account_list_result
  become: yes
  become_user: "{{ stereum_user }}"

- name: Fail on error
  fail:
    msg: "{{ account_list_result.stdout }}"
  when:
    - account_list_result.rc != 0
    - account_list_result.stdout is not search("no wallet found")

- name: List validators
  debug:
    msg: "{{ account_list_result.stdout }}"

# EOF
