---
- name: Check wallet.age exists
  stat:
    path: /tmp/exported-config/wallet.age
  register: wallet_age
  become: yes

- name: Decrypt wallet.age file
  ansible.builtin.expect:
    command: /usr/local/bin/age/age -d --output /tmp/exported-config/wallet.gz /tmp/exported-config/wallet.age
    timeout: "300"
    responses:
       Enter passphrase: "{{ exported_config_password | quote }}"
  become: yes
  when: wallet_age.stat.exists

- name: Unarchive wallet.gz
  ansible.builtin.unarchive:
    src: /tmp/exported-config/wallet.gz
    dest: /tmp/exported-config
    remote_src: yes
  become: yes
  when: wallet_age.stat.exists

- name: Copy password files into exported-config directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp/exported-config
    mode: '0755'
    remote_src: yes
  with_fileglob:
    - "/tmp/exported-config/wallet/*-passphrase.txt"  
  become: yes
  when: wallet_age.stat.exists

- name: Remove password files from wallet dir
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/tmp/exported-config/wallet/*-passphrase.txt"  
  become: yes
  when: wallet_age.stat.exists

# EOF
