---
- name: Download latest blockchain snapshot
  get_url:
    url: "https://fastsync.stereum.cloud/lighthouse/lighthouse-latest.tar.gz"
    dest: "/tmp/lighthouse-latest.tar.gz"
    mode: '0644'
  become: yes

- name: Deflate blockchain snapshot archive
  unarchive:
    src: "/tmp/lighthouse-latest.tar.gz"
    dest: "{{ e2dc_install_path }}/data/sigmaprime/"
  become: yes

- name: Delete snapshot archive
  file:
    state: absent
    path: "/tmp/lighthouse-latest.tar.gz"
  become: yes

- name: Set correct permission and owner/group of restored snapshot
  file:
    path: "{{ e2dc_install_path }}/data/sigmaprime/"
    state: directory
    owner: "stereum"
    group: "stereum"
    recurse: yes
  become: yes

# EOF
