---
- name: Install unzip
  apt:
    name: unzip
    update_cache: yes

- name: Install expect
  apt:
    name: expect
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install expect
  yum:
    name: expect
    state: latest
  when: ansible_distribution == "CentOS"    

- name: Download age
  get_url:
    url: https://github.com/FiloSottile/age/releases/download/v1.0.0-rc.1/age-v1.0.0-rc.1-linux-amd64.tar.gz
    dest: /tmp/age.gz
    mode: '0655'
  become: yes

- name: Extract '/tmp/age.gz' to '/usr/local/bin'
  ansible.builtin.unarchive:
    src: /tmp/age.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes

- name: Remove '/tmp/age.gz' file
  ansible.builtin.file:
    path: /tmp/age.gz
    state: absent
  become: yes    

- name: Unzip exported-config.zip file
  ansible.builtin.unarchive:
    src: "{{ exported_config_path }}"
    dest: /tmp
    remote_src: yes
  become: yes

- name: Decrypt exported-config.age file
  ansible.builtin.expect:
    command: /usr/local/bin/age/age -d --output /tmp/exported-config/ethereum2.yaml /tmp/exported-config/exported_config.age
    timeout: "300"
    responses:
       Enter passphrase: "{{ exported_config_password | quote }}"
  become: yes  

- name: Check wallet.age exists
  stat:
    path: /tmp/exported-config/wallet.age
  register: wallet_age
  become: yes

- name: Decrypt wallet.age file
  ansible.builtin.expect:
    command: /usr/local/bin/age/age -d --output /tmp/exported-config/wallet.gz /tmp/exported-config/wallet.age
    timeout: "300"
    responses:
       Enter passphrase: "{{ exported_config_password | quote }}"
  become: yes
  when: setup == "multiclient" and wallet_age.stat.exists

- name: Unarchive wallet.gz
  ansible.builtin.unarchive:
    src: /tmp/exported-config/wallet.gz
    dest: /tmp/exported-config
    remote_src: yes
  become: yes
  when: setup == "multiclient" and wallet_age.stat.exists

- name: Copy password files into exported-config directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp/exported-config
    mode: '0755'
    remote_src: yes
  with_fileglob:
    - "/tmp/exported-config/wallet/*-passphrase.txt"  
  become: yes
  when: setup == "multiclient" and wallet_age.stat.exists

- name: Remove password files from wallet dir
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/tmp/exported-config/wallet/*-passphrase.txt"  
  become: yes
  when: setup == "multiclient" and wallet_age.stat.exists     

- name: Set exported-config dir's permission
  ansible.builtin.file:
    path: /tmp/exported-config
    mode: '755'
    recurse: yes
  become: yes  

- name: Write imported config file
  ansible.builtin.copy:
    src: /tmp/exported-config/ethereum2.yaml
    dest: /etc/stereum
    mode: '0755'
    remote_src: yes
  become: yes  

- name: Remove exported-config directory
  file: 
    path: "/tmp/exported-config" 
    state: absent
  when: validator_password is not defined

# EOF      
