---
- name: Export config - ethereum2.yaml file
  shell: echo "{{ export_config_password | quote }}" | gpg -c --output /tmp/exported-config/exported_config.gpg --batch --yes --passphrase-fd 0 ethereum2.yaml
  args:
    chdir: "/etc/stereum/"
  become: yes

- name: Set exported config file's permission
  command: "chmod -R 755 /tmp/exported-config"
  become: yes

# EOF
