---
- name: Install pip, expect
  apt:
    update_cache: yes
    name:
      - python3-pip
      - expect
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install pip, expect
  yum:
    name:
      - python3-pip
      - expect
    state: latest
  when: ansible_distribution == "CentOS"

- name: Set correct permissions
  ansible.builtin.file:
    path: "{{ e2dc_install_path }}/data/nimbus/validator"
    owner: "2000"
    group: "2000"
    mode: '0700'
    state: directory

- name: Run import
  shell: "./nimbus_validator_import.sh {{ validator_password | quote }}" 
  args:
    chdir: "{{ e2dc_install_path }}"
  register: import_output   
  vars:
    ansible_python_interpreter: /bin/python3
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined

- name: error incorrect password
  fail:
    msg: "Incorrect Password!!! Please check your validator password and try it again."
  become: yes
  when: "'The entered password was incorrect' in import_output.stdout"

- name: error empty password
  fail:
    msg: "Password is empty!"
  become: yes
  when: import_output.stdout == ""

# EOF
