---
- name: Prysm - Configure correct public ip address
  lineinfile:
    path: "{{ e2dc_install_path }}/config/prysm/beacon.yaml"
    regexp: '^p2p-host-ip: '
    line: 'p2p-host-ip: {{ ansible_default_ipv4.address }}'
  become: yes
  become_user: "{{ stereum_user }}"
