---
- name: Ansible on CentOS
  include_tasks: ansible-centos.yaml
  when: ansible_distribution == "CentOS"

- name: Ansible on Ubuntu
  include_tasks: ansible-ubuntu.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# EOF