---
- name: Install expect
  apt:
    name: expect

- name: Run delete validator
  shell: "{{ e2dc_install_path }}/prysm_validator_delete.sh {{ validator_pubkey }}"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: yes
  when: setups[setup].delete_account is defined
