---
- name: Install expect
  apt:
    name: expect
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install expect
  yum:
    name: expect
    state: latest
  when: ansible_distribution == "CentOS"

- name: Run delete validator
  shell: "{{ e2dc_install_path }}/prysm_validator_delete.sh {{ validator_pubkey }}"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: yes
  when: setups[setup].delete_account is defined

- name: Separate 0x from public key
  shell: "printf {{ validator_pubkey }} | tail -c 96"
  register: pubkey_without_0x
  become: yes

- name: Remove keystore file from launchpad
  shell: "grep -l {{ pubkey_without_0x.stdout_lines[0] }} * | xargs rm"
  args:
    chdir: "{{ e2dc_install_path }}/launchpad"
  become: yes

# EOF  
