---
- name: Install expect
  apt:
    name: expect
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install expect
  yum:
    name: expect
    state: latest
  when: ansible_distribution == "CentOS"

- name: Run exit validator
  shell: "{{ e2dc_install_path }}/teku_validator_exit.sh \"{{ validator_keystore }}\""
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: yes
  register: exit_output
  when: setups[setup].exit_account is defined

- fail:
    msg: 'Validator is not active'
  become: yes
  when: exit_output.stdout is search('fails process voluntary exit conditions Validator is not active')
