---
- name: Install the latest version of yum-utils, curl
  yum:
    name:
      - yum-utils
      - curl
      - epel-release
    state: latest

- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/

- name: Install docker-ce
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
    state: latest
    disable_gpg_check: yes

- name: Install pip's docker-compose
  pip:
    name: docker-compose
    executable: pip3

# EOF