---
- name: Docker on CentOS
  include_tasks: docker-centos.yaml
  when: ansible_distribution == "CentOS"

- name: Docker on Ubuntu
  include_tasks: docker-ubuntu.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Generate docker's daemon.json
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: 644

- name: enable service docker
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started

- name: add stereum user to docker group
  user:
    name: "{{ stereum_user }}"
    groups: docker
    append: yes

# EOF